### ISSUE TITLE
Github activities still not pushed to Slack

### ISSUE THREAD

**Issue by Willian-Zhang** [Puriney/ineedabike#3]
I'm not adding it cus i don't have the privilege.
![image](https://cloud.githubusercontent.com/assets/5165840/19541287/26d132b0-9633-11e6-941c-f6e20ee611eb.png)

FYI, for those who do:
![image](https://cloud.githubusercontent.com/assets/5165840/19541297/3a6992ea-9633-11e6-8026-5d95beddcc6a.png)

**Comment by Willian-Zhang** [comment]
@Puriney

**Comment by Willian-Zhang** [comment]
FYI , if you want to do it:
![image](https://cloud.githubusercontent.com/assets/5165840/19541378/c291d592-9633-11e6-9e73-588db1479fd3.png)

**Comment by Puriney** [comment]
For something long story to discuss, Slack is worse than Issue. Slack is for instant message mainly to get people informed about certain hotfix, emergent bug, etc. We barely  have such a need thus I am not going to incorporate Slack.

**Comment by Willian-Zhang** [comment]
fine, i'm going to dismiss the group of slack.
I was picking it just because i want notification and timeline instead of a bunch of emails of GitHub activities.
but It's okey if you don't want to.

**Comment by Puriney** [comment]
Notification is good thing. I just tried, and Slack still requires access to private repo?! I thought it changed the service requirement already. Hmm, I would give up Slack.

**Comment by Willian-Zhang** [comment]
no it does not.
use `no auth` method, which's using GitHub `webhook` ( what i've posted above)

**Comment by Willian-Zhang** [comment]
however unfortunately , i deleted slack team of us.
