### ISSUE TITLE
Deadline for Final Report

### ISSUE THREAD

**Issue by Puriney** [Puriney/ineedabike#6]
@Willian-Zhang  Add your "explore new station" part to final project by 9PM Dec 14, so that we can have some time to compile the final version before midnight. The final due is 9AM Dec 15. 

My part is available at latest commit on master branch: https://github.com/Puriney/ineedabike/tree/a04e78a2d1405f1925fd750e9b67770680a40f2c

**Comment by Puriney** [comment]
I know you have big data to be processed. Here is suggested steps for you to follow to avoid uploading large file to GitHub:

1. Follow the instruction on the html report to download the data required by my part which is a 7MB zip which would be a csv (44.5MB) once unzipped.
2. Compile the RMD to see whether your environment works. It takes <5 minutes on my old computer.
3. Add your part to RMD.
4. Compile the RMD to generate the html.

I suggest you write bash file similar to my `get_data.sh` to leave the burden of downloading data to TA. We just need the compiled html.

**Comment by Willian-Zhang** [comment]
I'd commit my previous build 49c04f7 for now, and leave the final one to 12 Dec late PM / 13 Dev late PM

**Comment by Puriney** [comment]
Add some paragraph to elaborate on your data analysis, instead of codes and figures only. I will not wait for your part by 9 PM today.  I did not see your updates as you planed on either Dec 12 or Dec 13. Tomorrow morning is the due.

**Comment by Willian-Zhang** [comment]
Sorry for making a mistake on dates,
Good news is
I'm working on it.
